//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ktr_msc_ls1_BCM.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

  
    public partial class ProfileAddion :Profile
    {
        public new int Id { get; set; }
        public new string Firstname { get; set; }
        public new string Lastname { get; set; }
        public new string Company { get; set; }
        public new string Email { get; set; }
        public new Nullable<int> Phonenumber { get; set; }
      
      
    }
}
