//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ktr_msc_ls1_BCM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profiles_Library
    {
        public int Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Company { get; set; }
        public string Email { get; set; }
        public Nullable<int> Phonenumber { get; set; }
        public string PL_Status { get; set; }
        public int Profile_ID { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
